version: "3.8"

services:
  allmanager-docs:
    container_name: allmanager-docs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Evita problemas de dependências do host
    command: ["npx", "mintlify", "dev"]
